---
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
#knitr::opts_chunk$set(include = FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(fig.width = 11)

library("tidyverse");theme_set(theme_bw())
```

# Progress Report 10-21

Memory Efficiency in Distributed Data types.

\pagebreak

Since Last time
====

- [x] Fixed Bug

- [x] Re-ran Same Trials

- [x] Ran Some Longer Trials

- [x] Analysis of Results

\pagebreak

```{r, include=TRUE, fig.height = 3, fig.width = 5}
exp <- "longertests-data/"

csv <- read.csv("longertests.csv")
csv <- csv %>% 
    arrange(file_name) %>%
    mutate(file_name = paste(file_name, ".csv", sep="")) %>%
    filter(eager_rate != 50)
    
    #filter(duration == 300, merge_rate == 10)
#> unique(csv$num_nodes)
#[1]  2  3  4  5 10 15 20

data <- as_tibble(c())

for (i in 1:length(csv$file_name)) {

    temp <- read.csv(paste(exp, csv$file_name[i], sep=""))
    temp$node_id = as.factor(temp$node_id)

    print(ggplot(temp, aes(x = duration, y = items, color = node_id)) +
        geom_point() +
        geom_path() +
        ggtitle(paste("eager_rate =", csv$eager_rate[i])))

    #temp <- temp %>% mutate(merge_rate = csv$merge_rate[i],
    #                        num_nodes = csv$num_nodes[i],
    #                        eager_rate = csv$eager_rate[i])
    #data <- bind_rows(data, temp)


    #csv$node_id <- as.factor(csv$node_id)
}
#data$eager_rate = as.factor(data$eager_rate)
#data$num_nodes = as.factor(data$num_nodes)
#data$merge_rate = as.factor(data$merge_rate)


```
```{r, include=TRUE}

data <- as_tibble(c())

for (i in 1:length(csv$file_name)) {

    temp <- read.csv(paste(exp, csv$file_name[i], sep=""))

    temp <- temp %>% mutate(merge_rate = csv$merge_rate[i],
                            num_nodes = csv$num_nodes[i],
                            eager_rate = csv$eager_rate[i])
    data <- bind_rows(data, temp)


}
data <- data %>%
    filter(eager_rate != -1) %>%
    arrange(duration)
data$eager_rate = as.factor(data$eager_rate)
data$num_nodes = as.factor(data$num_nodes)
data$merge_rate = as.factor(data$merge_rate)
levels(data$eager_rate) = c("Aggressive", "Medium",
                            "Low", "Casual")

#"No Collection", "No Collection", "No Collection", 
ggsave("out.png", height=7, width=12, units="in")
```
```{r}
fit <- data %>% filter(duration > 1000, duration < 3600) %>% 
        filter(eager_rate != "No Collection") %>% 
        lm(items ~ duration, data = .)

fit1 <- data %>% filter(duration > 1000, duration < 3600) %>%
        filter(eager_rate == "No Collection") %>% 
        lm(items ~ duration, data = .)

fit2 <- data %>% filter(duration > 1000, duration < 3600) %>%
        filter(eager_rate == "Casual") %>% 
        lm(items ~ duration, data = .)

fit2half <- data %>% filter(duration > 1000, duration < 3600) %>%
        filter(eager_rate != "Casual") %>% 
        lm(items ~ duration, data = .)

fit3 <- data %>% filter(duration > 1000, duration < 3600) %>%
        filter(eager_rate == "Low") %>% 
        lm(items ~ duration, data = .)

fit4 <- data %>% filter(duration > 1000, duration < 3600) %>%
        filter(eager_rate == "Medium") %>% 
        lm(items ~ duration, data = .)

fit5 <- data %>% filter(duration > 1000, duration < 3600) %>%
        filter(eager_rate == "Aggressive") %>% 
        lm(items ~ duration, data = .)

    #annotate("text", x = 150, y = fit2$coefficients["(Intercept)"] + 300, label = paste("Slope:", fit1$coefficients["duration"])) +
ggplot(data , aes(x = duration, y = items, color = eager_rate)) +
    geom_point() +
    geom_path() +
    geom_abline(slope = fit2$coefficients["duration"], intercept = fit2$coefficients["(Intercept)"]) +
    geom_abline(slope = fit2half$coefficients["duration"], intercept = fit2half$coefficients["(Intercept)"]) +
    #annotate("text", x = 200, y = 4000, label = paste("y =",round(digits=2, fit1$coefficients["(Intercept)"]),"+", round(fit1$coefficients["duration"], digits=2), "x")) +
    #annotate("text", x = 500, y = 0, label = paste("Slope:", fit$coefficients["duration"])) +
    annotate("text", x = 150, y = fit2$coefficients["(Intercept)"] + 150, label = "Casual Collection") +
    annotate("text", x = 150, y = fit2half$coefficients["(Intercept)"] - 100, label = "Eager Collection") +
    labs(x = "Duration (s)", y = "Items", color = "Collection Type") +
    ggtitle("Comparison of Collection Types.")
```
```{r}
data$eager_rate <- case_when(data$eager_rate == "Casual" ~ 0,
                             data$eager_rate != "Casual" ~ 1)
hyptest <- data %>% filter(duration > 1000, duration < 3600) %>%
    lm(items ~ duration + eager_rate + (eager_rate*duration), data = .)


```

```{r data, include=TRUE, fig.height = 3, fig.width = 5}
exp <- "175tests2-data/"

csv <- read.csv("175tests2.csv")
csv <- csv %>% 
    arrange(file_name) %>%
    mutate(file_name = paste(file_name, ".csv", sep="")) %>%
    filter(duration == 300, num_nodes == 5)
#> unique(csv$num_nodes)
#[1]  2  3  4  5 10 15 20

data <- as_tibble(c())

for (i in 1:length(csv$file_name)) {

    temp <- read.csv(paste(exp, csv$file_name[i], sep=""))
    #temp$node_id = as.factor(temp$node_id)

    #print(ggplot(temp, aes(x = duration, y = items, color = node_id)) +
    #    geom_point() +
    #    geom_path() +
    #    ggtitle(paste("eager_rate =", csv$eager_rate[i])))

    temp <- temp %>% mutate(merge_rate = csv$merge_rate[i],
                            num_nodes = csv$num_nodes[i],
                            eager_rate = csv$eager_rate[i])
    data <- bind_rows(data, temp)


    #csv$node_id <- as.factor(csv$node_id)
}
data$eager_rate = as.factor(data$eager_rate)
data$num_nodes = as.factor(data$num_nodes)
data$merge_rate = as.factor(data$merge_rate)


```
```{r, include=TRUE}
for (i in levels(data$merge_rate)) {
    print(data %>% filter(merge_rate == i) %>%
          ggplot(aes(x = duration, y = items, color = eager_rate)) +
            geom_point() +
            geom_path() +
            ggtitle(paste("num_nodes = 5 | merge_rate =", i)))
}

```
